import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'

const coffeeStore = () => {
    const router = useRouter()
    const id = router.query.id
  return (
    <div>
        <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
        Coffee Store Page {id}
        <div>
        <Link href="/"><a>Back to Home</a></Link>
        <br/>
        <Link href="/coffee-store/dynamic"><a>Go to dynamic page</a></Link>
        <br/>
        <Link href="/coffee-store/foobar"><a>Go to foobar page</a></Link>
        </div>

      </div>
    
    </div>
  )
}

export default coffeeStore